### ISSUE TITLE
We need a true README.md

### ISSUE THREAD

**Issue by Bromind** [Treast/forum_rails#1]
Tell the world what is your project. Use a readme  : 
- [ ] What do your project ?
- [ ] How to install ?
- [ ] How it works ?
- [ ] Is it based on another project ?
- [ ] etc...

**Comment by Treast** [comment]
Hum... Ok.

**Comment by Bromind** [comment]
What the hell is that? I never wrote that comment! In particular on Feb 19, 2015.

**Comment by Treast** [comment]
You did my bro, you did ...
